"""The agentify contract, re-checked on every `make check`.

The level comes from .agentify.toml; `agentify adopt --level N` raises it.
Generated by agentify; safe to edit, but the check itself lives upstream.
"""

from pathlib import Path

from agentify.config import load_config
from agentify.contract import FAIL, run_checks
from agentify.repo import Repo

ROOT = Path(__file__).resolve().parent.parent


def test_contract_holds_at_declared_level():
    level = load_config(ROOT).level
    assert level >= 1, ".agentify.toml declares no contract level"
    failing = [r for r in run_checks(Repo.open(ROOT), level) if r.status == FAIL]
    assert not failing, "\n".join(f"{r.item}: {r.reason}" for r in failing)
